### ISSUE TITLE
environment for Angular.js

### ISSUE THREAD

**Issue by hoony-o-1** [codeforseoul/-deprecated-showcase#1]
@corneadoug are there any libraries you use mainly like ui-router?

**Comment by corneadoug** [comment]
Never used ui-router before, but it looks cool

**Comment by chaabaj** [comment]
i used ui-router and its very good library. It support nested views:+1:

**Comment by hoony-o-1** [comment]
right. stateProvider is much better than routeProvider to me. But It's the first time to use angular.js on gem for me, so that I think I need to study more

**Comment by chaabaj** [comment]
Yes maybe we don't need if we generate the views in the server and use just angular in the generated page

**Comment by hoony-o-1** [comment]
@chaabaj you're right. which way is better, @mozodev ? Angular router or Rails router?

**Comment by mozodev** [comment]
In my humble opinion, wouldn't it be better that rails could be used just for backend api and angular takes whole control of frontend.

**Comment by corneadoug** [comment]
That's usually how it works
